# Generated by Django 3.0.1 on 2019-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0002_auto_20191230_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentoffer',
            name='slug',
        ),
        migrations.AddField(
            model_name='currentoffer',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
