# Generated by Django 3.0.1 on 2019-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0003_auto_20191230_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentoffer',
            name='offerImage',
            field=models.ImageField(null=True, upload_to='shopUser/'),
        ),
    ]
