# Generated by Django 3.0.1 on 2019-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0004_currentoffer_offerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentoffer',
            name='offerImage',
            field=models.ImageField(null=True, upload_to='OfferImage/'),
        ),
    ]
