# Generated by Django 3.0.1 on 2019-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0005_auto_20191230_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categoryImage', models.ImageField(null=True, upload_to='categoryImage/')),
            ],
        ),
    ]
