# Generated by Django 3.0.1 on 2020-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='myproduct', unique=True),
            preserve_default=False,
        ),
    ]
