# Generated by Django 3.0.1 on 2020-01-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0008_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
