# Generated by Django 3.0.1 on 2020-01-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0011_auto_20200109_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
