# Generated by Django 3.0.1 on 2020-01-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0015_auto_20200109_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='my-category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='my-product'),
        ),
    ]
