# Generated by Django 3.0.1 on 2020-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0018_auto_20200114_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_by',
            field=models.IntegerField(default=0),
        ),
    ]
