# Generated by Django 3.0.1 on 2020-01-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0019_product_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_from',
            field=models.CharField(default='noakhali', max_length=200),
            preserve_default=False,
        ),
    ]
