# Generated by Django 3.0.1 on 2020-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0021_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
