# Generated by Django 3.0.1 on 2020-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0023_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default='+8801', max_length=20),
        ),
    ]
