# Generated by Django 3.0.1 on 2020-02-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopUser', '0024_order_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='dhaka,Mohammadpur', max_length=200),
            preserve_default=False,
        ),
    ]
